/**
 * Insight Types
 *
 * Foundational types for the proactive insights system.
 * Insights are AI-generated observations about the user's financial data
 * that help them make better decisions.
 */

/**
 * Types of insights that can be generated
 */
export type InsightType =
  | 'anomaly_spending' // Unusual spending detected
  | 'anomaly_income' // Unusual income pattern
  | 'subscription_change' // Subscription price changed
  | 'new_recurring' // New recurring charge detected
  | 'budget_warning' // Approaching budget limit
  | 'cash_flow_warning' // Cash flow issue predicted
  | 'invoice_overdue' // Invoice past due
  | 'payment_received' // Large payment received
  | 'tax_deadline' // Tax deadline approaching
  | 'savings_opportunity' // Money saving opportunity found
  | 'benchmark_comparison' // Spending vs industry average
  | 'goal_progress'; // Progress toward financial goal

/**
 * Severity levels for insights
 */
export type InsightSeverity = 'info' | 'warning' | 'alert' | 'positive';

/**
 * Status of an insight
 */
export type InsightStatus = 'new' | 'read' | 'dismissed' | 'expired';

/**
 * An insight generated by the system
 */
export interface Insight {
  id: string;
  workspaceId: string;
  type: InsightType;
  severity: InsightSeverity;
  title: string;
  message: string;
  data: Record<string, unknown>;
  actionUrl?: string;
  actionLabel?: string;
  createdAt: Date;
  readAt?: Date;
  dismissedAt?: Date;
  expiresAt?: Date;
}

/**
 * Input for creating a new insight
 */
export interface CreateInsightInput {
  workspaceId: string;
  type: InsightType;
  severity: InsightSeverity;
  title: string;
  message: string;
  data?: Record<string, unknown>;
  actionUrl?: string;
  actionLabel?: string;
  expiresAt?: Date;
}

/**
 * Summary statistics for insights
 */
export interface InsightsSummary {
  total: number;
  unread: number;
  bySeverity: Record<InsightSeverity, number>;
  byType: Partial<Record<InsightType, number>>;
}

/**
 * Options for fetching insights
 */
export interface GetInsightsOptions {
  workspaceId: string;
  filter?: 'all' | 'unread' | 'dismissed';
  types?: InsightType[];
  severities?: InsightSeverity[];
  limit?: number;
  offset?: number;
}

/**
 * Default severity for each insight type
 */
export const DEFAULT_INSIGHT_SEVERITY: Record<InsightType, InsightSeverity> = {
  anomaly_spending: 'warning',
  anomaly_income: 'info',
  subscription_change: 'warning',
  new_recurring: 'info',
  budget_warning: 'alert',
  cash_flow_warning: 'alert',
  invoice_overdue: 'alert',
  payment_received: 'positive',
  tax_deadline: 'warning',
  savings_opportunity: 'positive',
  benchmark_comparison: 'info',
  goal_progress: 'info',
};

/**
 * Get human-readable label for insight type
 */
export function getInsightTypeLabel(type: InsightType): string {
  const labels: Record<InsightType, string> = {
    anomaly_spending: 'Spending Anomaly',
    anomaly_income: 'Income Anomaly',
    subscription_change: 'Subscription Change',
    new_recurring: 'New Recurring Payment',
    budget_warning: 'Budget Warning',
    cash_flow_warning: 'Cash Flow Warning',
    invoice_overdue: 'Overdue Invoice',
    payment_received: 'Payment Received',
    tax_deadline: 'Tax Deadline',
    savings_opportunity: 'Savings Opportunity',
    benchmark_comparison: 'Benchmark Comparison',
    goal_progress: 'Goal Progress',
  };
  return labels[type];
}

/**
 * Get color for insight severity (for UI)
 */
export function getInsightSeverityColor(severity: InsightSeverity): {
  bg: string;
  text: string;
  border: string;
} {
  const colors: Record<InsightSeverity, { bg: string; text: string; border: string }> = {
    info: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
    warning: { bg: 'bg-yellow-50', text: 'text-yellow-700', border: 'border-yellow-200' },
    alert: { bg: 'bg-red-50', text: 'text-red-700', border: 'border-red-200' },
    positive: { bg: 'bg-green-50', text: 'text-green-700', border: 'border-green-200' },
  };
  return colors[severity];
}

/**
 * Get icon name for insight type (for UI)
 */
export function getInsightTypeIcon(type: InsightType): string {
  const icons: Record<InsightType, string> = {
    anomaly_spending: 'TrendingUp',
    anomaly_income: 'TrendingDown',
    subscription_change: 'RefreshCw',
    new_recurring: 'Repeat',
    budget_warning: 'AlertTriangle',
    cash_flow_warning: 'AlertCircle',
    invoice_overdue: 'Clock',
    payment_received: 'DollarSign',
    tax_deadline: 'Calendar',
    savings_opportunity: 'PiggyBank',
    benchmark_comparison: 'BarChart2',
    goal_progress: 'Target',
  };
  return icons[type];
}

/**
 * Calculate insights summary from a list of insights
 */
export function calculateInsightsSummary(insights: Insight[]): InsightsSummary {
  const summary: InsightsSummary = {
    total: insights.length,
    unread: 0,
    bySeverity: {
      info: 0,
      warning: 0,
      alert: 0,
      positive: 0,
    },
    byType: {},
  };

  for (const insight of insights) {
    // Count unread
    if (!insight.readAt && !insight.dismissedAt) {
      summary.unread++;
    }

    // Count by severity
    summary.bySeverity[insight.severity]++;

    // Count by type
    summary.byType[insight.type] = (summary.byType[insight.type] || 0) + 1;
  }

  return summary;
}

/**
 * Check if an insight has expired
 */
export function isInsightExpired(insight: Insight): boolean {
  if (!insight.expiresAt) return false;
  return new Date() > insight.expiresAt;
}

/**
 * Get the status of an insight
 */
export function getInsightStatus(insight: Insight): InsightStatus {
  if (insight.dismissedAt) return 'dismissed';
  if (isInsightExpired(insight)) return 'expired';
  if (insight.readAt) return 'read';
  return 'new';
}
